project:
  type: website

website:
  title: "Policy, Politics, and Data"
  site-url: https://www.natekratzer.com/
  description: "A data science blog"
  google-analytics: G-9PPZMMCZD8
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/natekratzer
      - icon: threads
        href: https://www.threads.net/@nate_kratzer
  margin-header: subscribe.html

format:
  html:
    theme: litera
    css: styles.css
comments: 
  utterances: 
    repo: natekratzer/blog_comments

execute:
  freeze: auto
  




