project:
  type: website

website:
  title: "Nate Kratzer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/natekratzer
      - icon: mastodon
        href: https://fosstodon.org/@natekratzer
format:
  html:
    theme: cerulean
    css: styles.css



