[project]
name = "personal-quarto-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "jupyter>=1.1.1",
    "palmerpenguins>=0.1.4",
    "pandas>=2.2.3",
]
